### ISSUE TITLE
Test xhprof_008.phpt fails on s390x

### ISSUE THREAD

**Issue by andypost** [longxinH/xhprof#15]
I have no such hardware to make sure why it fails but Alpinelinux build system reported

```
FAILED TEST SUMMARY
---------------------------------------------------------------------
XHProf: Sampling Mode Test
Author: kannan [tests/xhprof_008.phpt]
```

Current log http://build.alpinelinux.org/buildlogs/build-edge-s390x/testing/php7-xhprof/php7-xhprof-2.0.2-r0.log

**Comment by longxinH** [comment]
You can show me xhprof_008.diff and xhprof_008.log ?

**Comment by longxinH** [comment]
@andypost My PHP version

**Comment by longxinH** [comment]
@andypost Do you have to configure xhprof.sampling_interval?

**Comment by longxinH** [comment]
@andypost Try the latest master branch

**Comment by andypost** [comment]
> Do you have to configure xhprof.sampling_interval?
No, I did not, any suggestion for default setting?

**Comment by andypost** [comment]
I can't access build logs to get what's wrong with the test but I pushing patch from your last commit to test it on build machine

**Comment by andypost** [comment]
As readme said `sampling_interval` has default 100000 so I just added this 2 default settings https://github.com/alpinelinux/aports/blob/master/testing/php7-xhprof/APKBUILD#L35

**Comment by longxinH** [comment]
I fixed a memory leak at noon, you tried the latest master branch
https://github.com/longxinH/xhprof/commit/6507a35d72e9598700e37208c482329594fd3b41

**Comment by longxinH** [comment]
Does the build machine have a way to export xhprof_008.diff and xhprof_008.log?

**Comment by andypost** [comment]
I just pushed commit (for memory leak as patch) and in 10-15 mins should get results from builders

**Comment by longxinH** [comment]
@andypost ok?

**Comment by andypost** [comment]
@longxinH not yet, something weird with build system right now

**Comment by ncopa** [comment]
I have access to an Alpine Linux s390x system and I can reproduce it.
````
$ cat ./extension/tests/xhprof_008.diff
001+ Test failed
001- Test passed
002+ Count of usleep samples in one call to goo(): 0
003+ Count of usleep samples in two calls to goo(): 0
004+ Samples in one call to goo(): 
005+ array(8) {
006+   ["1533668216.600000"]=>
007+   string(6) "usleep"
008+   ["1533668216.700000"]=>
009+   string(6) "usleep"
010+   ["1533668216.800000"]=>
011+   string(6) "usleep"
012+   ["1533668216.900000"]=>
013+   string(6) "usleep"
014+   ["1533668217.000000"]=>
015+   string(6) "usleep"
016+   ["1533668217.100000"]=>
017+   string(6) "usleep"
018+   ["1533668217.200000"]=>
019+   string(6) "usleep"
020+   ["1533668217.300000"]=>
021+   string(6) "usleep"
022+ }
023+ Samples in two calls to goo(): 
024+ array(16) {
025+   ["1533668217.400000"]=>
026+   string(6) "usleep"
027+   ["1533668217.500000"]=>
028+   string(6) "usleep"
029+   ["1533668217.600000"]=>
030+   string(6) "usleep"
031+   ["1533668217.700000"]=>
032+   string(6) "usleep"
033+   ["1533668217.800000"]=>
034+   string(6) "usleep"
035+   ["1533668217.900000"]=>
036+   string(6) "usleep"
037+   ["1533668218.000000"]=>
038+   string(6) "usleep"
039+   ["1533668218.100000"]=>
040+   string(6) "usleep"
041+   ["1533668218.200000"]=>
042+   string(6) "usleep"
043+   ["1533668218.300000"]=>
044+   string(6) "usleep"
045+   ["1533668218.400000"]=>
046+   string(6) "usleep"
047+   ["1533668218.500000"]=>
048+   string(6) "usleep"
049+   ["1533668218.600000"]=>
050+   string(6) "usleep"
051+   ["1533668218.700000"]=>
052+   string(6) "usleep"
053+   ["1533668218.800000"]=>
054+   string(6) "usleep"
055+   ["1533668218.900000"]=>
056+   string(6) "usleep"
057+ }
$ cat ./extension/tests/xhprof_008.log

---- EXPECTED OUTPUT
Test passed
---- ACTUAL OUTPUT
Test failed
Count of usleep samples in one call to goo(): 0
Count of usleep samples in two calls to goo(): 0
Samples in one call to goo(): 
array(8) {
  ["1533668216.600000"]=>
  string(6) "usleep"
  ["1533668216.700000"]=>
  string(6) "usleep"
  ["1533668216.800000"]=>
  string(6) "usleep"
  ["1533668216.900000"]=>
  string(6) "usleep"
  ["1533668217.000000"]=>
  string(6) "usleep"
  ["1533668217.100000"]=>
  string(6) "usleep"
  ["1533668217.200000"]=>
  string(6) "usleep"
  ["1533668217.300000"]=>
  string(6) "usleep"
}
Samples in two calls to goo(): 
array(16) {
  ["1533668217.400000"]=>
  string(6) "usleep"
  ["1533668217.500000"]=>
  string(6) "usleep"
  ["1533668217.600000"]=>
  string(6) "usleep"
  ["1533668217.700000"]=>
  string(6) "usleep"
  ["1533668217.800000"]=>
  string(6) "usleep"
  ["1533668217.900000"]=>
  string(6) "usleep"
  ["1533668218.000000"]=>
  string(6) "usleep"
  ["1533668218.100000"]=>
  string(6) "usleep"
  ["1533668218.200000"]=>
  string(6) "usleep"
  ["1533668218.300000"]=>
  string(6) "usleep"
  ["1533668218.400000"]=>
  string(6) "usleep"
  ["1533668218.500000"]=>
  string(6) "usleep"
  ["1533668218.600000"]=>
  string(6) "usleep"
  ["1533668218.700000"]=>
  string(6) "usleep"
  ["1533668218.800000"]=>
  string(6) "usleep"
  ["1533668218.900000"]=>
  string(6) "usleep"
}
---- FAILED
````

**Comment by ncopa** [comment]
that was with 6507a35d72e9598700e37208c482329594fd3b41 applied.

**Comment by longxinH** [comment]
This problem is a bit tricky. The value value should be ```main()==>goo==>bar==>foo==>usleep```, but only ```usleep``` is obtained. The environment of s390x I don't know how to build it now, and I can't reproduce it.

**Comment by andypost** [comment]
I gonna setup lxc for s390x and dig sampling, probably 100000 is not enough
Last time https://github.com/google/benchmark/blob/v1.1.0/src/cycleclock.h helped to fix tideways for ppc64

**Comment by longxinH** [comment]
The output key is correct, the sampling interval is also correct, the error appears in the value, and the previous part is lost. This is my output
```
array(8) {
  ["1533720384.300000"]=>
  string(33) "main()==>goo==>bar==>foo==>usleep"
  ["1533720384.400000"]=>
  string(33) "main()==>goo==>bar==>foo==>usleep"
  ["1533720384.500000"]=>
  string(33) "main()==>goo==>bar==>foo==>usleep"
  ["1533720384.600000"]=>
  string(33) "main()==>goo==>bar==>foo==>usleep"
  ["1533720384.700000"]=>
  string(33) "main()==>goo==>bar==>foo==>usleep"
  ["1533720384.800000"]=>
  string(33) "main()==>goo==>bar==>foo==>usleep"
  ["1533720384.900000"]=>
  string(33) "main()==>goo==>bar==>foo==>usleep"
  ["1533720385.000000"]=>
  string(33) "main()==>goo==>bar==>foo==>usleep"
}

array(16) {
  ["1533720551.500000"]=>
  string(33) "main()==>goo==>bar==>foo==>usleep"
  ["1533720551.600000"]=>
  string(33) "main()==>goo==>bar==>foo==>usleep"
  ["1533720551.700000"]=>
  string(33) "main()==>goo==>bar==>foo==>usleep"
  ["1533720551.800000"]=>
  string(33) "main()==>goo==>bar==>foo==>usleep"
  ["1533720551.900000"]=>
  string(33) "main()==>goo==>bar==>foo==>usleep"
  ["1533720552.000000"]=>
  string(33) "main()==>goo==>bar==>foo==>usleep"
  ["1533720552.100000"]=>
  string(33) "main()==>goo==>bar==>foo==>usleep"
  ["1533720552.200000"]=>
  string(33) "main()==>goo==>bar==>foo==>usleep"
  ["1533720552.300000"]=>
  string(33) "main()==>goo==>bar==>foo==>usleep"
  ["1533720552.400000"]=>
  string(33) "main()==>goo==>bar==>foo==>usleep"
  ["1533720552.500000"]=>
  string(33) "main()==>goo==>bar==>foo==>usleep"
  ["1533720552.600000"]=>
  string(33) "main()==>goo==>bar==>foo==>usleep"
  ["1533720552.700000"]=>
  string(33) "main()==>goo==>bar==>foo==>usleep"
  ["1533720552.800000"]=>
  string(33) "main()==>goo==>bar==>foo==>usleep"
  ["1533720552.900000"]=>
  string(33) "main()==>goo==>bar==>foo==>usleep"
  ["1533720553.000000"]=>
  string(33) "main()==>goo==>bar==>foo==>usleep"
}

Test passed
```

**Comment by longxinH** [comment]
My guess is https://github.com/longxinH/xhprof/blob/master/extension/xhprof.c#L506, the definition is size_t but the actual return is char*, there will be different results in s390x, no determine

**Comment by andypost** [comment]
Yep, this function looks strange cos I see no memory allocation for the string (maybe I miss something)

**Comment by longxinH** [comment]
Spprintf will allocate memory, so I am not sure if it is a return type problem.

**Comment by longxinH** [comment]
@andypost I fixed the type of return and try it out. https://github.com/longxinH/xhprof/commit/2522d0d3fe505a7f1cec655a0d9935d333a27c98

**Comment by andypost** [comment]
@longxinH I asked @ncopa to test it again and he said it  still fails

PS: I misread sprintf ( you are right http://www.phpinternalsbook.com/php7/internal_types/strings/printing_functions.html#you-don-t-know-your-buffer-size

**Comment by ncopa** [comment]
test still fails.

It looks like `hp_inline_hash` works differently on big-endian machines (like s390x). I don't know if it matters.

**Comment by longxinH** [comment]
```hp_inline_hash``` is mainly used to calculate the hash value when the filter function is set.

**Comment by longxinH** [comment]
@ncopa Thanks, it is possible that the hp_inline_hash function has different results on s390x, I tried to modify it from here.

**Comment by longxinH** [comment]
@andypost @ncopa try it https://github.com/longxinH/xhprof/commit/b712f929f8096f679f5dfdd148579cc88203dc45

**Comment by andypost** [comment]
@ncopa I added 2nd patch https://github.com/alpinelinux/aports/pull/4975

**Comment by ncopa** [comment]
b712f92 looks right, so hash algorithm should be same on s390x (equally effective) but unfortunately does not solve our problem. Test still fails. :disappointed:

**Comment by longxinH** [comment]
I am very sorry that only the real environment gdb has been debugged, but I have no s390x system here.

**Comment by andypost** [comment]
Used to enable for 2.1.2 version and it still fails https://gitlab.alpinelinux.org/andypost/aports/-/jobs/21166

**Comment by longxinH** [comment]
I have reproduced it here, it will be fixed in the near future, thanks for feedback

**Comment by longxinH** [comment]
@andypost Hi, please verify that the latest master is successful

**Comment by andypost** [comment]
@longxinH Thank you a lot - nice oneliner fix!
Now it passed https://gitlab.alpinelinux.org/alpine/aports/merge_requests/1986/diffs pushed the change!

**Comment by andypost** [comment]
There's 2 commits in master with release 2.1.3 - @longxinH are you going to upload it to pecl?

**Comment by longxinH** [comment]
正在使用发音

OK, no problem. I'll update to PECL tomorrow morning

Andy Postnikov <notifications@github.com>于2019年12月11日 周三00:39写道：

**Comment by longxinH** [comment]
@andypost https://pecl.php.net/package/xhprof/2.1.3
